### ISSUE TITLE
Unable to install apk.

### ISSUE THREAD

**Issue by sunnykatiyar50** [Palatis/XAppDebug#1]
Getting apk not installed error. When tried root installation getting something like INSTALL_FAILED_TEST_ONLY error.

**Comment by yujincheng08** [comment]
Same issue here. Android Q.

I compile it myself and it could be installed like a charm. I think there some problems of the releasing compilation.

**Comment by Palatis** [comment]
I'll dig into this when I get some free time.
being busy for the few months.

**Comment by Palatis** [comment]
after all this is probably a gradle bug.

https://stackoverflow.com/questions/25274296/adb-install-fails-with-install-failed-test-only
